language: node_js
node_js: 
  - 12.18.3
jobs:
  include:
    - stage: deploy
      provider: heroku
      user: "tolulopeaiyegbusi@gmail.com"
      api_key: 
        secure: $HEROKU_API_KEY
      app: $HEROKU_APP_NAME
      on:
        branch: main

